'use client';

import { create } from 'zustand';
import { persist, createJSONStorage, type StateStorage } from 'zustand/middleware';
import { get, set, del } from 'idb-keyval';

// ---------------------------------------------------------------------------
// IndexedDB-backed StateStorage adapter (via idb-keyval)
// ---------------------------------------------------------------------------
// localStorage has a ~5 MB limit which is easily exceeded when storing
// base64-encoded images. IndexedDB offers hundreds of MB+ of quota.
const indexedDBStorage: StateStorage = {
  getItem: async (name: string): Promise<string | null> => {
    if (typeof window === 'undefined') return null;
    return (await get(name)) ?? null;
  },
  setItem: async (name: string, value: string): Promise<void> => {
    if (typeof window === 'undefined') return;
    await set(name, value);
  },
  removeItem: async (name: string): Promise<void> => {
    if (typeof window === 'undefined') return;
    await del(name);
  },
};

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SalesStrategy {
  executiveSummary: string;
  marketingPlan: {
    targetAudience: string;
    salesDescription: string;
  };
}

export interface PricePoints {
  min: number;
  max: number;
  realisticFast: number;
  realisticOptimal: number;

  realisticSlow: number;
}

export interface MarketAnalysis {
    currency: string;
    newPrice: PricePoints;
    usedPrice: PricePoints;
    forRepairPrice: PricePoints;
    forPartsPrice: PricePoints;
    forScrapPrice: PricePoints;
    analysisJustification: string;
}

export interface InventoryItem {
  id: string;
  productName: string;
  productType?: string;
  category: string;
  condition: string;
  conditionJustification: string;
  marketAnalysis: MarketAnalysis;
  salesStrategy?: SalesStrategy;
  createdAt: number;
  originalImageDataUri?: string; // The original image uploaded by the user
  presentationImages?: string[]; // Studio-quality images generated by AI
}

interface InventoryState {
  items: InventoryItem[];

  /** Indicates whether the persisted state has been loaded from disk. */
  _hasHydrated: boolean;

  addItem: (item: InventoryItem) => void;
  removeItem: (id: string) => void;
  updateItem: (id: string, updates: Partial<Omit<InventoryItem, 'id'>>) => void;
  getItem: (id: string) => InventoryItem | undefined;
  clearInventory: () => void;

  /** Internal — called by the persist middleware after rehydration completes. */
  setHasHydrated: (value: boolean) => void;
}

// ---------------------------------------------------------------------------
// One-time migration helper: localStorage → IndexedDB
// ---------------------------------------------------------------------------
const OLD_STORAGE_KEY = 'marketsight-ai-inventory-storage-v7';

/**
 * If data still lives under the old localStorage key, move it into IndexedDB
 * so existing users don't lose their inventory on the first load after the
 * upgrade.
 */
async function migrateFromLocalStorage(newKey: string): Promise<void> {
  try {
    if (typeof window === 'undefined') return;
    if (!window.localStorage) return;
    
    const raw = window.localStorage.getItem(OLD_STORAGE_KEY);
    if (!raw) return; // Nothing to migrate

    // Write the raw JSON blob to IndexedDB under the new key (only if IDB
    // doesn't already contain data for it).
    const existing = await get(newKey);
    if (!existing) {
      await set(newKey, raw);
    }

    // Clean up the old key so this migration is a one-shot operation.
    window.localStorage.removeItem(OLD_STORAGE_KEY);
  } catch (e) {
    // Silently fail on SSR or if localStorage is inaccessible
    console.warn('[inventory-store] localStorage → IndexedDB migration failed or skipped:', e);
  }
}

// ---------------------------------------------------------------------------
// Store
// ---------------------------------------------------------------------------
const STORAGE_KEY = 'marketsight-ai-inventory-idb-v1';
const SCHEMA_VERSION = 1;

// Kick off the one-time migration as early as possible (runs on module load on
// the client side; the await is consumed by the persist middleware which reads
// from IDB asynchronously anyway).
if (typeof window !== 'undefined') {
  migrateFromLocalStorage(STORAGE_KEY);
}

export const useInventoryStore = create<InventoryState>()(
  (set, get) => ({
    items: [],
    _hasHydrated: true, // manually set to true since no hydration

    addItem: (item) => set((state) => ({ items: [item, ...state.items] })),

    removeItem: (id) =>
      set((state) => ({
        items: state.items.filter((item) => item.id !== id),
      })),

    updateItem: (id, updates) =>
      set((state) => ({
        items: state.items.map((item) =>
          item.id === id ? { ...item, ...updates } : item,
        ),
      })),

    getItem: (id: string) => {
      return get().items.find((item) => item.id === id);
    },

    clearInventory: () => set({ items: [] }),

    setHasHydrated: (value) => set({ _hasHydrated: value }),
  })
);
